### ISSUE TITLE
ClientUWS's POST actions fail

### ISSUE THREAD

**Issue by gmella** [SITools2/Astronomy-Extension-Server#8]
Hi,
I tried to create a job using fr.cnes.sitools.extensions.astro.application.uws.client.ClientUWS, but restlet library and Form post request as application/x-www-form-urlencoded . This hurts my uws server on top of UWSLib framework (https://github.com/gmantele/taplib)

I succeeded to workarround the use of restlet Form by using FormDataSet and multipart request.

Did you experiment this code with success ?
## Cheers,

Guillaume

**Comment by J-Christophe** [comment]
Hi Guillaume,

What is(are) the problem(s) ? It is :
- a bug from the ClientUWS,
- a problem with the implementation of the standard (I do not think
  because Post request as application/x-www-form-urlencoded is part of the
  standard)
- a contribution for ClientUWS.
- a bug in your UWS implementation

Thanks,
Jean-Christophe

**Comment by gmella** [comment]
Hi Jean-Christophe,

 I just look in the UWSlib written by G. Mantelet and application/x-www-form-urlencoded seem supported.
This was more a question from a newbie to get a confirmation from your side that you are fine with your client code.

I will look more into details on my implementation using the libUWS servlet material.

## Regards,

Guillaume

**Comment by J-Christophe** [comment]
Hi Guillaume,

Thanks for your reply. Yes I am fine on my code for UWS 1.0 because I
tested it for my UWS server. If the standard could provide a WADL, this
could help a lot the developers but it is not the case.

In addition, it is written here in the UWS standard (version 1.0) :
2.1.11. Parameter List

[...]
1. HTTP POST an _application/x-www-form-urlencoded_ parameter name,
   value pair to either
   1. /{jobs}/{job-id}
   2. /{jobs}/{job-id}/parameters
2. HTTP PUT the parameter value to /{jobs}/{job-id}/parameters/(
   parameter-name)

Regards,

Jean-Christophe
